### ISSUE TITLE
Ajuda para a lista 3

### ISSUE THREAD

**Issue by lnrdsrv** [julia-nosralla/Lista-3-CE2#5]
Favor verificar a estrutura do projeto e a sintaxe do arquivo Lista_3.R

**Comment by julia-nosralla** [comment]
Iza, você pode ver isso pra mim? @Izadebora

**Comment by Izadebora** [comment]
Ana, você pode ver isso pra mim? @AnalyceRayssa

**Comment by AnalyceRayssa** [comment]
Opa, já verifiquei! @lnrdsrv ficou bom??
